/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JFrame;
/**
 *
 * @author Jessica
 */
public class Menu extends javax.swing.JFrame {
    
    private static Menu sMenu;
    int total;
    private double price;
    

    public static Menu getInstance(){
        if(sMenu == null){
            sMenu = new Menu();
        }
        return sMenu;
    }
    
    public int getTotal() {
        return total;
    }

    public void addToTotal(int num) {
        total += num;
    }
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        price = 0;
        total = 0;
        buyBugs.setVisible(false);
        buyNavy.setVisible(false);
        buyTotally.setVisible(false);
        buyAmazing.setVisible(false);
        buyFlow.setVisible(false);
        BugsMachineDescription.setVisible(false);
        NavyDogDescription.setVisible(false);
        TotallyDogDescription.setVisible(false);
        AmazingGraceDescription.setVisible(false);
        FlowSodaDescription.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BugsMachine = new javax.swing.JButton();
        NavyDog = new javax.swing.JButton();
        TotallyDog = new javax.swing.JButton();
        AmazingGrace = new javax.swing.JButton();
        FlowSoda = new javax.swing.JButton();
        hopperDogsMenuTitle = new javax.swing.JLabel();
        buyBugs = new javax.swing.JButton();
        BugsMachineDescription = new javax.swing.JLabel();
        NavyDogDescription = new javax.swing.JLabel();
        TotallyDogDescription = new javax.swing.JLabel();
        AmazingGraceDescription = new javax.swing.JLabel();
        FlowSodaDescription = new javax.swing.JLabel();
        buyNavy = new javax.swing.JButton();
        buyTotally = new javax.swing.JButton();
        buyAmazing = new javax.swing.JButton();
        buyFlow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BugsMachine.setText("Bugs in Machine $2.50");
        BugsMachine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugsMachineActionPerformed(evt);
            }
        });

        NavyDog.setText("Navy Bean Veggie Dog $5.25");
        NavyDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavyDogActionPerformed(evt);
            }
        });

        TotallyDog.setText("Totally Compiled Dog $7.50");
        TotallyDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotallyDogActionPerformed(evt);
            }
        });

        AmazingGrace.setText("Amazing Grace $4.50");
        AmazingGrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmazingGraceActionPerformed(evt);
            }
        });

        FlowSoda.setText("Flow-Matic Original Soda $2.25");
        FlowSoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlowSodaActionPerformed(evt);
            }
        });

        hopperDogsMenuTitle.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        hopperDogsMenuTitle.setText("Hopper Dogs Menu");

        buyBugs.setText("Buy");
        buyBugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBugsActionPerformed(evt);
            }
        });

        BugsMachineDescription.setText("Battered and fried edible insects with our spicy dip");

        NavyDogDescription.setText("The best veggie dog in town");

        TotallyDogDescription.setText("Everything you could want on your all beef hotdog - cheese, chilli and bacon!");

        AmazingGraceDescription.setText("Vanilla bean cheesecake with caramel sauce");

        FlowSodaDescription.setText("Our small batch cream soda dispensed from our super-chilled fountain");

        buyNavy.setText("Buy");
        buyNavy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyNavyActionPerformed(evt);
            }
        });

        buyTotally.setText("Buy");
        buyTotally.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTotallyActionPerformed(evt);
            }
        });

        buyAmazing.setText("Buy");
        buyAmazing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyAmazingActionPerformed(evt);
            }
        });

        buyFlow.setText("Buy");
        buyFlow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyFlowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(hopperDogsMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TotallyDog, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BugsMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NavyDog))
                    .addComponent(FlowSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmazingGrace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BugsMachineDescription)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buyBugs)
                                .addGap(85, 85, 85)))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NavyDogDescription)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyTotally)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyAmazing)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AmazingGraceDescription)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FlowSodaDescription)
                            .addComponent(TotallyDogDescription))
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyNavy)
                        .addGap(252, 252, 252))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyFlow)
                        .addGap(227, 227, 227))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(hopperDogsMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(BugsMachine, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NavyDog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BugsMachineDescription)
                        .addGap(18, 18, 18)
                        .addComponent(buyBugs)
                        .addGap(18, 18, 18)
                        .addComponent(NavyDogDescription)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyNavy)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TotallyDogDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyTotally)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TotallyDog, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AmazingGraceDescription)
                        .addComponent(buyAmazing))
                    .addComponent(AmazingGrace, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlowSodaDescription)
                    .addComponent(FlowSoda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buyFlow)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BugsMachineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugsMachineActionPerformed
        BugsMachineDescription.setVisible(true);
        NavyDogDescription.setVisible(false);
        TotallyDogDescription.setVisible(false);
        AmazingGraceDescription.setVisible(false);
        FlowSodaDescription.setVisible(false);
        buyBugs.setVisible(true);
        buyNavy.setVisible(false);
        buyTotally.setVisible(false);
        buyAmazing.setVisible(false);
        buyFlow.setVisible(false);
        price = 2.50;
    }//GEN-LAST:event_BugsMachineActionPerformed

    private void NavyDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavyDogActionPerformed
        NavyDogDescription.setVisible(true);
        BugsMachineDescription.setVisible(false);
        TotallyDogDescription.setVisible(false);
        AmazingGraceDescription.setVisible(false);
        FlowSodaDescription.setVisible(false);
        buyBugs.setVisible(false);
        buyNavy.setVisible(true);
        buyTotally.setVisible(false);
        buyAmazing.setVisible(false);
        buyFlow.setVisible(false);
        price = 5.25;
    }//GEN-LAST:event_NavyDogActionPerformed

    private void TotallyDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotallyDogActionPerformed
        TotallyDogDescription.setVisible(true);
        BugsMachineDescription.setVisible(false);
        NavyDogDescription.setVisible(false);
        AmazingGraceDescription.setVisible(false);
        FlowSodaDescription.setVisible(false);
        buyBugs.setVisible(false);
        buyNavy.setVisible(false);
        buyTotally.setVisible(true);
        buyAmazing.setVisible(false);
        buyFlow.setVisible(false);
        price = 7.50;
    }//GEN-LAST:event_TotallyDogActionPerformed

    private void AmazingGraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmazingGraceActionPerformed
        AmazingGraceDescription.setVisible(true);
        BugsMachineDescription.setVisible(false);
        NavyDogDescription.setVisible(false);
        TotallyDogDescription.setVisible(false);
        FlowSodaDescription.setVisible(false);
        buyBugs.setVisible(false);
        buyNavy.setVisible(false);
        buyTotally.setVisible(false);
        buyAmazing.setVisible(true);
        buyFlow.setVisible(false);
        price = 4.50;
    }//GEN-LAST:event_AmazingGraceActionPerformed

    private void FlowSodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlowSodaActionPerformed
        FlowSodaDescription.setVisible(true);
        BugsMachineDescription.setVisible(false);
        NavyDogDescription.setVisible(false);
        TotallyDogDescription.setVisible(false);
        AmazingGraceDescription.setVisible(false);
        buyBugs.setVisible(false);
        buyNavy.setVisible(false);
        buyTotally.setVisible(false);
        buyAmazing.setVisible(false);
        buyFlow.setVisible(true);
        price = 2.25;
    }//GEN-LAST:event_FlowSodaActionPerformed

    private void buyBugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBugsActionPerformed
        this.dispose();
        JFrame buyBugsQuantity = new BuyQuantity(2.50, "Bugs in the Machine");
        buyBugsQuantity.setVisible(true);
    }//GEN-LAST:event_buyBugsActionPerformed

    private void buyNavyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyNavyActionPerformed
        this.dispose();
        JFrame buyBugsQuantity = new BuyQuantity(5.25, "Navy Bean Veggie Dog");
        buyBugsQuantity.setVisible(true);
    }//GEN-LAST:event_buyNavyActionPerformed

    private void buyTotallyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTotallyActionPerformed
        this.dispose();
        JFrame buyBugsQuantity = new BuyQuantity(7.50, "Totally Compiled Dog");
        buyBugsQuantity.setVisible(true);
    }//GEN-LAST:event_buyTotallyActionPerformed

    private void buyAmazingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyAmazingActionPerformed
        this.dispose();
        JFrame buyBugsQuantity = new BuyQuantity(4.50, "Amazing Grace");
        buyBugsQuantity.setVisible(true);
    }//GEN-LAST:event_buyAmazingActionPerformed

    private void buyFlowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyFlowActionPerformed
        this.dispose();
        JFrame buyBugsQuantity = new BuyQuantity(2.25, "Flow-Matic Original Soda");
        buyBugsQuantity.setVisible(true);
    }//GEN-LAST:event_buyFlowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmazingGrace;
    private javax.swing.JLabel AmazingGraceDescription;
    private javax.swing.JButton BugsMachine;
    private javax.swing.JLabel BugsMachineDescription;
    private javax.swing.JButton FlowSoda;
    private javax.swing.JLabel FlowSodaDescription;
    private javax.swing.JButton NavyDog;
    private javax.swing.JLabel NavyDogDescription;
    private javax.swing.JButton TotallyDog;
    private javax.swing.JLabel TotallyDogDescription;
    private javax.swing.JButton buyAmazing;
    private javax.swing.JButton buyBugs;
    private javax.swing.JButton buyFlow;
    private javax.swing.JButton buyNavy;
    private javax.swing.JButton buyTotally;
    private javax.swing.JLabel hopperDogsMenuTitle;
    // End of variables declaration//GEN-END:variables
}
